### 1. ตรวจสอบว่ามี libary ของ numpy อยู่ในเครื่องหรือไม่

In [ ]:
!pip show numpy

2. ถ้าไม่มีให้ทำการติดตั้ง libary ของ numpy โดยใช้คำสั่ง `!pip install numpy`

In [ ]:
! pip install numpy

### 3. สร้าง Array 1 มิติ ที่มีขนาด 10 และเก็บค่า 0 ทุกตำแหน่ง

In [ ]:
import numpy as np

row = np.array([1, 2, 3]) # 1 row, 3 columns
column = np.array([[1], [2], [3]]) # 3 rows, 1 column

print(row)

print(column)

matrix = np.array([[1, 2], [3, 4], [5, 6]]) # 3 rows, 2 columns

print(matrix)

In [ ]:
### random numbers

int = np.random.randint(1,5,5)
r2 = np.random.random(5)
random = np.random.rand(3, 2) # 3 rows, 2 columns

print(random)
print(int)
print(r2)

In [18]:
vrow = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(vrow) # แสดงข้อมูลทั้งหมด
print(vrow[0]) # แสดงข้อมูลตำแหน่งที่ 0
print(vrow[2:6]) # แสดงข้อมูลตำแหน่งที่ 2 ถึง 6
print(vrow[2:]) # แสดงข้อมูลตำแหน่งที่ 2 ถึงสุดท้าย
print(vrow[:6]) # แสดงข้อมูลตำแหน่งแรก ถึง 6
print(vrow[-1]) # แสดงข้อมูลตำแหน่งสุดท้าย
print(vrow[-3]) # แสดงข้อมูลตำแหน่งที่ 3 นับจากท้าย
print(vrow[-3:-1])  # แสดงข้อมูลตำแหน่งที่ 3 ถึง 1 นับจากท้าย

[ 1  2  3  4  5  6  7  8  9 10]
1
[3 4 5 6]
[ 3  4  5  6  7  8  9 10]
[1 2 3 4 5 6]
10
8
[8 9]


### การหาค่าทางสถิติใน numpy สามารถทำได้โดยใช้ฟังก์ชันต่างๆ ดังนี้

In [33]:
stat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(stat)

print("Max: ", np.max(stat))
print("Min: ", stat.min())
print("Mean:", np.mean(stat))
print("Median:", np.median(stat))   # หาค่ามัธยฐาน หรือค่ากลาง
print("Std", np.std(stat))  # หาค่าเบี่ยงเบนมาตรฐาน
print("Variance", np.var(stat))  # หาค่าความแปรปรวน



[[1 2 3]
 [4 5 6]
 [7 8 9]]
Max:  9
Min:  1
Mean: 5.0
Median: 5.0
Std 2.581988897471611
Variance 6.666666666666667
